version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - node --version  # Imprime la versión de Node.js
      - npm --version   # Imprime la versión de npm
      - npm install
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
  build:
    commands:
      - echo Building the application...
      - ng build --prod
artifacts:
  files:
    - '**/*'
  base-directory: dist/prueba-aws-code-pipe-line
