version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --prod
artifacts:
  files:
    - 'dist/**/*'
  base-directory: dist
